### PR TITLE
PRO-3188 log-all-routes

### PR DESCRIPTION
**Pull request by boutell**
Documentation for APOS_LOG_ALL_ROUTES. This has landed in apostrophe main. Please do not merge and deploy docs until feature released (this coming Wednesday).

### CODE REVIEW

**Review by BoDonkey — APPROVED** [review]
No substantive comment. The "be reaching" could be "reach", but that is more of a personal style comment.

**Comment by boutell** [comment]
Thanks, I took that tip.

**Comment by boutell** [comment]
Aaand I merged it. Backing out.

**Comment by boutell** [comment]
I reverted it. I'll make a note to un-revert it on Wednesday.

**Pull request merged**
